### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by willin** [creativelive/hapi-ratelimit#22]
After install this plugin, no data return:

![qq20160711-0 2x](https://cloud.githubusercontent.com/assets/1890238/16717389/166b48dc-4748-11e6-997c-0b74d146fa16.png)

When out of range: 

app crash:

```
message: Uncaught error: Cannot read property 'error' of undefined
stack: TypeError: Uncaught error: Cannot read property 'error' of undefined
    at /Users/willin/Documents/wulian/v3/push/node_modules/.npminstall/hapi-ratelimit/0.2.1/hapi-ratelimit/lib/index.js:51:30
    at done (/Users/willin/Documents/wulian/v3/push/node_modules/.npminstall/ratelimiter/2.0.1/ratelimiter/index.js:97:7)
    at /Users/willin/Documents/wulian/v3/push/node_modules/.npminstall/ratelimiter/2.0.1/ratelimiter/index.js:110:9
    at /Users/willin/Documents/wulian/v3/push/node_modules/.npminstall/redis/0.10.3/redis/index.js:1138:13
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at try_callback (/Users/willin/Documents/wulian/v3/push/node_modules/.npminstall/redis/0.10.3/redis/index.js:573:9)
    at RedisClient.return_reply (/Users/willin/Documents/wulian/v3/push/node_modules/.npminstall/redis/0.10.3/redis/index.js:661:13)
    at ReplyParser.<anonymous> (/Users/willin/Documents/wulian/v3/push/node_modules/.npminstall/redis/0.10.3/redis/index.js:309:14)
    at emitOne (events.js:96:13)
```

**Comment by willin** [comment]
``` js
    "authcode": "latest",
    "babel-plugin-transform-runtime": "^6.6.0",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-es2015-loose": "^7.0.0",
    "babel-preset-stage-1": "^6.5.0",
    "babel-register": "^6.7.2",
    "babel-runtime": "^6.6.1",
    "boom": "^3.1.2",
    "canvas": "^1.4.0",
    "captcha": "^0.0.4",
    "debug": "^2.2.0",
    "good": "^6.6.3",
    "handlebars": "^4.0.5",
    "hapi": "^13.2.1",
    "hapi-swagger-plugins": "latest",
    "hoek": "^4.0.0",
    "inert": "^3.2.0",
    "jianzhou-sdk": "latest",
    "joi": "^8.0.4",
    "marked": "^0.3.5",
    "maxmind": "^1.1.0",
    "moment": "^2.13.0",
    "moment-timezone": "^0.5.2",
    "newrelic": "^1.27.2",
    "node-uuid": "^1.4.7",
    "promise-redis": "0.0.5",
    "superagent": "^2.0.0",
    "through2": "^2.0.1",
    "vision": "^4.1.0",
    "waliyun": "latest"
```
